### ISSUE TITLE
Git clone error

### ISSUE THREAD

**Issue by Oseni03** [matorral-project/matorral#128]
### Operating System

Window 11

### Description

Getting the error below when trying to clone the repo

Cloning into 'matorral'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Oseni03** [comment]
I would love to contribute to this project

**Comment by matagus** [comment]
Hey @Oseni03! How are you cloning the repository?

**Comment by matagus** [comment]
@Oseni03 please try this `git clone https://github.com/matorral-project/matorral.git`

You will need to setup your ssh key if you'd like to commit / push to this repo. See instructions [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) or feel free to reopen this issue.

**Comment by matagus** [comment]
@Oseni03 did that work for you?
